-- imports
local colours = require("D3vanagar1.plugins.theme.colours")
-- local lsp = require("feline.providers.lsp")
-- local vi_mode_uitils = require("feline.providers.vi_mode")

--constants
local vi_mode_colours = {
    NORMAL = colours.green,
    INSERT = colours.red,
    VISUAL = colours.magenta,
    OP = colours.green,
    BLOCK = colours.blue,
    REPLACE = colours.violet,
    ["V-REPLACE"] = colours.violet,
    ENTER = colours.cyan,
    SELECT = colours.orange,
    COMMAND = colours.green,
    TERM = colours.green,
    NONE = colours.darkblue,
    MORE = colours.cyan,
}

-- TODO: components not working. Whole statusline turns black if enabled
-- local icons = {
--     linux = " ",
--     macos = " ",
--     windows = " ",
--
--     errs = " ",
--     warns = " ",
--     infos = " ",
--     hints = " ",
--
--     lsp = " ",
--     git = "",
-- }
--
-- --functions
-- local function lsp_diagnostic_info()
--     return {
--         errs = lsp.get_diagnostics_count("Error"),
--         warns = lsp.get_diagnostics_count("Warning"),
--         infos = lsp.get_diagnostics_count("Information"),
--         hints = lsp.get_diagnostics_count("Hint"),
--     }
-- end
--
-- local function diag_of(f, s)
--     local icon = icons[s]
--     return function()
--         local diag = f()[s]
--         return icon .. diag
--     end
-- end
--
-- local function diag_enable(f, s)
--     return function()
--         local diag = f()[s]
--         return diag and diag ~= 0
--     end
-- end
--
-- local function vimode_hl()
--     return {
--         name = vi_mode_uitils.get_mode_highlight_name(),
--         fg = vi_mode_uitils.get_mode_color(),
--     }
-- end
--
-- local function file_osinfo()
--     local os = vim.bo.fileformat:upper()
--     local icon
--     if os == "MAC" then
--         icon = icons.macos
--     elseif os == "UNIX" then
--         icon = icons.linux
--     else
--         icon = icons.windows
--     end
--     return icon .. os
-- end
--
-- local comps = {
--     vi_mode = {
--         left = {
--             provider = "▊",
--             hl = vimode_hl,
--             right_sep = " ",
--         },
--         right = {
--             provider = "▊",
--             hl = vimode_hl,
--             left_sep = " ",
--         },
--     },
--     line_percentage = {
--         provider = "line_percentage",
--         left_sep = " ",
--         hl = {
--             style = "bold",
--         },
--     },
--     scroll_bar = {
--         provider = "scroll_bar",
--         left_sep = " ",
--         hl = {
--             fg = colours.blue,
--             style = "bold",
--         },
--     },
--     file = {
--         info = {
--             provider = "file_info",
--             hl = {
--                 fg = colours.blue,
--                 style = "bold",
--             },
--         },
--         encoding = {
--             provider = "file_enocding",
--             left_sep = " ",
--             hl = {
--                 fg = colours.violet,
--                 style = "bold",
--             },
--         },
--         type = {
--             provider = "file_type",
--         },
--         os = {
--             provider = file_osinfo,
--             left_sep = " ",
--             hl = {
--                 fg = colours.violet,
--                 style = "bold",
--             },
--         },
--     },
--     diagnos = {
--         err = {
--             provider = diag_of(lsp_diagnostic_info, "errs"),
--             left_sep = " ",
--             enabled = diag_enable(lsp_diagnostic_info, "errs"),
--             hi = {
--                 fg = colours.red,
--             },
--         },
--         warn = {
--             provider = diag_of(lsp_diagnostic_info, "warns"),
--             left_sep = " ",
--             enabled = diag_enable(lsp_diagnostic_info, "warns"),
--             hi = {
--                 fg = colours.yellow,
--             },
--         },
--         info = {
--             provider = diag_of(lsp_diagnostic_info, "infos"),
--             left_sep = " ",
--             enabled = diag_enable(lsp_diagnostic_info, "infos"),
--             hi = {
--                 fg = colours.blue,
--             },
--         },
--         hint = {
--             provider = diag_of(lsp_diagnostic_info, "hints"),
--             left_sep = " ",
--             enabled = diag_enable(lsp_diagnostic_info, "hints"),
--             hi = {
--                 fg = colours.cyan,
--             },
--         },
--     },
--     lsp = {
--         name = {
--             provider = "lsp_client_names",
--             left_sep = " ",
--             icon = icons.lsp,
--             hl = {
--                 fg = colours.yellow,
--             },
--         },
--     },
--     git = {
--         branch = {
--             provider = "git_branch",
--             icon = icons.git,
--             left_sep = " ",
--             hl = {
--                 fg = colours.violet,
--                 style = "bold",
--             },
--         },
--         add = {
--             provider = "git_diff_added",
--             hl = {
--                 fg = colours.green,
--             },
--         },
--         change = {
--             provider = "git_diff_changed",
--             hl = {
--                 fg = colours.orange,
--             },
--         },
--         remove = {
--             provider = "gitdiff_removed",
--             hl = {
--                 fg = colours.red,
--             },
--         },
--     },
-- }
--
-- local components = {
--     left = {
--         active = {
--             -- comps.vi_mode.left,
--             -- comps.file.info,
--             -- comps.lsp.name,
--             -- comps.diagnos.err,
--             -- comps.diagnos.warn,
--             -- comps.diagnos.hint,
--             -- comps.diagnos.info,
--         },
--         inactive = {
--             -- comps.file.info,
--             -- comps.vi_mode.left,
--         },
--     },
--     mid = {
--         active = {},
--         inactive = {},
--     },
--     right = {
--         active = {
--             -- comps.git.add,
--             -- comps.git.change,
--             -- comps.git.remove,
--             -- comps.file.os,
--             -- comps.git.branch,
--             -- comps.line_percentage,
--             -- comps.vi_mode.right,
--             -- comps.scroll_bar,
--         },
--         inactive = {},
--     },
-- }

require("feline").setup({
    default_bg = colours.bg,
    default_fg = colours.fg,
    -- components = components,
    vi_mode_colours = vi_mode_colours,
})
